name: Production

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via AZ Module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: List Function Applications
        run: |
          az functionapp list --output table
      - name: Pull our code
        uses: actions/checkout@v3
      - name: List Files
        run: ls -lah
      - name: Run DDL Scripts
        run: |
          cd database
          for file in ./*; do az postgres flexible-server execute -n ${{secrets.PG_SERVERNAME}} -u ${{secrets.PG_USERNAME}} -p ${{secrets.PG_PASSWORD}} -d ${{secrets.PG_DATABASE}} -f $file; done
          cd ..
      - name: Deploy Backend
        run: |
          cd functions
          ls -lah
          npm i -g azure-functions-core-tools@4 --unsafe-perm true
          func azure functionapp fetch-app-settings readosfu
          npm run deploy
          cd ..
      - name: Build Frontend
        run: |
          cd frontend
          npm i
          npm run build
          cd ..
      - name: Upload Frontend
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch -s '$web' --account-name readossa --connection-string ${{secrets.READOSSA_CONNSTR}}
            az storage blob upload-batch --account-name readossa --auth-mode key --overwrite true -d '$web' -s ./frontend/dist/reados --connection-string ${{secrets.READOSSA_CONNSTR}}
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "readoscdn" --name "reados" --resource-group "readosrg"
      - name: Logout from AZ
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

#  # This workflow contains a single job called "build"
#  build:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
#
#      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
